apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-webmvc-_TargetRole_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmvc
      release: eshop-webmvc
      role: _TargetRole_
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webmvc
        release: eshop-webmvc
        role: _TargetRole_
    spec:
      containers:
        - name: webmvc
          image: "creshoponcontainers.azurecr.io/eshop/webmvc:_ImageTag_"
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: OrchestratorType
              value: 'K8S'
            - name: IsClusterEnv
              value: 'True'
            - name: PATH_BASE
              value: "/webmvc"
            - name: k8sname
              value: "eshop-aks"
            - name: "ApplicationInsights__InstrumentationKey"
              valueFrom:
                configMapKeyRef:
                  key: "all__InstrumentationKey"
                  name: "cfg-eshop-webmvc"
            - name: "DPConnectionString"
              valueFrom:
                configMapKeyRef:
                  key: "webmvc__keystore"
                  name: "cfg-eshop-webmvc"
            - name: PurchaseUrl
              valueFrom:
                configMapKeyRef:
                  key: "internalurls__apigwws"
                  name: "cfg-eshop-webmvc"
            - name: ExternalPurchaseUrl
              valueFrom:
                configMapKeyRef:
                  key: "urls__apigwws"
                  name: "cfg-eshop-webmvc"
            - name: CallBackUrl
              valueFrom:
                configMapKeyRef:
                  key: "urls__mvc"
                  name: "cfg-eshop-webmvc"
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  key: "urls__IdentityUrl"
                  name: "cfg-eshop-webmvc"
            - name : IdentityUrlHC
              valueFrom:
                configMapKeyRef:
                  key: "internalurls__identity__hc"
                  name: "cfg-eshop-webmvc"
            - name: SignalrHubUrl
              valueFrom:
                configMapKeyRef:
                  key: "urls__apigwws"
                  name: "cfg-eshop-webmvc"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m 