apiVersion: v1
kind: Service
metadata:
  name: webmvc
  labels:
    app: webmvc
    chart: webmvc-0.1.0
    release: eshop-webmvc
    heritage: Helm
    role: _TargetRole_
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: webmvc
    release: eshop-webmvc
    role: _TargetRole_