apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-webmvc-_TargetRole_
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webmvc
      release: eshop-webmvc
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webmvc
        release: eshop-webmvc
        role: _TargetRole_
    spec:
      containers:
        - name: webmvc
          image: "creshoponcontainers.azurecr.io/eshop/webmvc:linux-latest"
          env:
            - name: MyDbContext
              value: "_ConnString_"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: OrchestratorType
              value: 'K8S'
            - name: IsClusterEnv
              value: 'True'
            - name: PATH_BASE
              value: "/webmvc"
            - name: k8sname
              value: "eshop-aks"
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                configMapKeyRef:
                  key: all__InstrumentationKey
            - name: DPConnectionString
              valueFrom:
                configMapKeyRef:
                  key: webmvc__keystore
            - name: PurchaseUrl
              valueFrom:
                configMapKeyRef:
                  key: internalurls__apigwws
            - name: ExternalPurchaseUrl
              valueFrom:
                configMapKeyRef:
                  key: urls__apigwws
            - name: CallBackUrl
              valueFrom:
                configMapKeyRef:
                  key: urls__mvc
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  key: urls__IdentityUrl
            - name : IdentityUrlHC
              valueFrom:
                configMapKeyRef:
                  key: internalurls__identity__hc
            - name: SignalrHubUrl
              valueFrom:
                configMapKeyRef:
                  key: urls__apigwws
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m 