apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-webmvc-_TargetRole_
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webmvc
      release: eshop-webmvc
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webmvc
        release: eshop-webmvc
        role: _TargetRole_
    spec:
      containers:
        - name: webmvc
          image: "creshoponcontainers.azurecr.io/eshop/webmvc:linux-latest"
          env:
            - name: MyDbContext
              value: "_ConnString_"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m