apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
      release: eshop-catalog-api
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: catalog-api
        release: eshop-catalog-api
        role: _TargetRole_
    spec:
      containers:
        - name: catalog-api
          image: "creshoponcontainers.azurecr.io/eshop/catalog.api:linux-latest"
          env:
            - name: MyDbContext
              value: "_ConnString_"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m