apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  labels:
    app: catalog-api
    chart: catalog-api-0.1.0
    release: eshop-catalog-api
    heritage: Helm
    role: _TargetRole_
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 81
      targetPort: grpc
      protocol: TCP
      name: grpc     
  selector:
    app: catalog-api
    release: eshop-catalog-ap
    role: _TargetRole_