apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
      release: eshop-basket-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: basket-api
        release: eshop-basket-api
    spec:
      containers:
        - name: basket-api
          image: "creshoponcontainers.azurecr.io/eshop/basket.api:linux-latest"
          env:
            - name: MyDbContext
              value: "_ConnString_"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m