# This is a basic workflow to help you get started with Actions
name: Blue-Green-promote-reject

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        type: string
      promote_reject:
        description: 'Promote or reject'
        required: true
        default: reject
        type: choice
        options:
        - reject
        - promote

env:
  RESOURCE_GROUP: 'rg-eShopOnContainers'
  AKS_CLUSTER_NAME: 'aks-eShopOnContainers'
  ACR_NAME: crdemoeastus

jobs:
  promote_reject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Set cluster context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - name: ACR login
        run: 'az acr login -n ${{ env.ACR_NAME }}'

      - name: Promote/reject
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            src/k8s/service.yaml
            src/k8s/deploy.yaml
          images: '${{ env.ACR_NAME }}.azurecr.io/${{ secrets.repository }}/app:${{ inputs.image_tag }}'
          strategy: blue-green
          action: ${{ inputs.promote_reject }}