# This is a basic workflow to help you get started with Actions
name: Blue-Green-promote-reject

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      service_file:
        description: 'Service file to promote or reject'
        required: true
        type: string
      #promote_reject:
      #  description: 'Promote or reject'
      #  required: true
      #  default: reject
      #  type: choice
      #  options:
      #  - reject
      #  - promote

env:
  RESOURCE_GROUP: 'rg-eShopOnContainers'
  AKS_CLUSTER_NAME: 'aks-eShopOnContainers'

jobs:
  promote_reject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - name: Deploy set context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.AZ_AKS_NAME }}
          resource-group: ${{ env.AZ_RG_NAME }}

      - name: Check Services Current Role
        run: |
          echo "Login Azure Services"
          az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" -t "${{ secrets.AZURE_TENANT_ID }}"

          echo "Set Azure Subscription"
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

          echo "Get credentials for AKS cluster"
          az aks get-credentials --resource-group "${{ env.AZ_RG_NAME }}" --name "${{ env.AZ_AKS_NAME }}" --admin --file kubeconfig

          echo "Logout Azure Services"
          az logout

          echo "Get current role"
          current_role="$(kubectl --kubeconfig kubeconfig get services webmvc -o=jsonpath='{.spec.selector.role}')"
          echo "Current role: $current_role"
          
          echo "Define new role"
          [[ $current_role = 'blue' ]] && newRole='green' || newRole='blue'
          echo "newRole: $newRole"

          echo "Replace role in k8s files"
          sed -i "s|_TargetRole_|$newRole|g" ${{ inputs.service_name }}

      # Deploy app to AKS
      - name: Deploy to k8s
        uses: azure/k8s-deploy@v4
        with:
          manifests: ${{ inputs.service_name }}
          namespace: default