# This is a basic workflow to help you get started with Actions
name: Blue-Green-promote-reject

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
env:
  AZ_RG_NAME: 'rg-eShopOnContainers'
  AZ_AKS_NAME: 'aks-eShopOnContainers'

jobs:
  promote_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Services Current Role
        run: |
          echo "Login Azure Services"
          az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" -t "${{ secrets.AZURE_TENANT_ID }}"

          echo "Set Azure Subscription"
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

          echo "Get credentials for AKS cluster"
          az aks get-credentials --resource-group "${{ env.AZ_RG_NAME }}" --name "${{ env.AZ_AKS_NAME }}" --admin --file kubeconfig

          echo "Logout Azure Services"
          az logout

          echo "Get current Build Number"
          greenDeployment="$(kubectl --kubeconfig kubeconfig get services catalog-api-green -o=jsonpath='{.spec.selector.app}')"
          
          echo "greenDeployment: $greenDeployment"
          kubectl --kubeconfig kubeconfig patch service catalog-api-green -p '"spec": {"selector": {"app": "$greenDeployment","release": "eshop-catalog-api"}}'