name: Blue/Green Catalog API - AKS

on: workflow_dispatch

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

env:
  AZ_RG_NAME: 'rg-eShopOnContainers'
  AZ_AKS_NAME: 'aks-eShopOnContainers'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_LOGIN }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Catalog API image
      uses: docker/build-push-action@v2.10.0
      with:
        context: src
        file: src/Services/Catalog/Catalog.API/Dockerfile
        tags: |
          ${{secrets.ACR_URL}}/eshop/catalog.api:${{ GITHUB.RUN_NUMBER }}
          ${{secrets.ACR_URL}}/eshop/catalog.api:linux-latest
        push: true
    
    - name: Replace variables
      run: |
        sed -i 's|_ImageTag_|${{ GITHUB.RUN_NUMBER }}|g' src/Services/Catalog/Catalog.API/kubernetes-catalog-api.yaml

    - name: Upload Kubernetes files
      uses: actions/upload-artifact@v3.0.0
      with:
        name: DEV
        path: src/Services/Catalog/Catalog.API/kubernetes-catalog-api.yaml
        
  release:
    needs: build
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Download k8s artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: DEV
          path: my-app-artifact
      
      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - name: Deploy set context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.AZ_AKS_NAME }}
          resource-group: ${{ env.AZ_RG_NAME }}

      # Deploy app to AKS
      - name: Deploy to k8s
        uses: azure/k8s-deploy@v1
        with:
          manifests: my-app-artifact/kubernetes-catalog-api.yaml
          namespace: default

      - name: Update Green Service
        run: |
          echo "Login Azure Services"
          az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" -t "${{ secrets.AZURE_TENANT_ID }}"

          echo "Set Azure Subscription"
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

          echo "Get credentials for AKS cluster"
          az aks get-credentials --resource-group "${{ env.AZ_RG_NAME }}" --name "${{ env.AZ_AKS_NAME }}" --admin --file kubeconfig

          echo "Logout Azure Services"
          az logout

          kubectl patch service catalog-api-green -p '"spec": {"selector": {"app": "catalog-api-${{ GITHUB.RUN_NUMBER }}","release": "eshop-catalog-api"}}'