name: Build and Release Web MVC

on: workflow_dispatch

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

env:
  AZ_RG_NAME: 'rg-eShopOnContainers'
  AZ_AKS_NAME: 'aks-eShopOnContainers'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_LOGIN }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Web MVC image
      uses: docker/build-push-action@v2.10.0
      with:
        context: src
        file: src/Web/WebMVC/Dockerfile
        tags: |
          ${{secrets.ACR_URL}}/eshop/webmvc:linux-latest
        push: true

    - name: Replace variables
      run: |
        sed -i 's|_ConnString_|${{ secrets.AZURE_SQL_CONNECTION }}|g' src/Web/WebMVC/kubernetes-web-mvc.yaml
        sed -i 's|_TargetRole_|blue|g' src/Web/WebMVC/kubernetes-web-mvc.yaml
        sed -i 's|_TargetRole_|blue|g' src/Web/WebMVC/kubernetes-web-mvc-service.yaml

    - name: Upload Kubernetes files
      uses: actions/upload-artifact@v3.0.0
      with:
        name: k8s
        path: |
          src/Web/WebMVC/kubernetes-web-mvc.yaml
          src/Web/WebMVC/kubernetes-web-mvc-service.yaml
        
  release:
    needs: build
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Download k8s artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: k8s
          path: my-app-artifact
      
      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - name: Deploy set context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.AZ_AKS_NAME }}
          resource-group: ${{ env.AZ_RG_NAME }}

      # Deploy app to AKS
      - name: Deploy to k8s
        uses: azure/k8s-deploy@v1
        with:
          manifests: my-app-artifact/kubernetes-web-mvc.yaml
          namespace: default